services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  userservice:
    build: ./userservice
    ports:
      - "8081:8081" # Map container port 4000 to localhost port 4000
    volumes:
      - ./userservice:/app # Mount the backend code so changes reflect
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "1090:1090" # Map container port 3000 to localhost port 3000
    volumes:
      - ./frontend:/app # Mount the frontend code so changes reflect
    environment:
      - NODE_ENV=development
    
  apigateway:
    build: ./apigateway
    ports:
      - "7878:7878" # Map container port 3000 to localhost port 3000
    volumes:
      - ./apigateway:/app # Mount the frontend code so changes reflect
    environment:
      - NODE_ENV=development
    depends_on:
      - frontend
      - userservice
